export const SIGN_IN_PENDING = 'SIGN_IN_PENDING';
export const SIGN_IN_FULFILLED = 'SIGN_IN_FULFILLED';
export const SIGN_IN_REJECTED = 'SIGN_IN_REJECTED';

export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_FULFILLED = 'SIGN_UP_FULFILLED';
export const SIGN_UP_REJECTED = 'SIGN_UP_REJECTED';
