export const MOVIES_PENDING = 'MOVIES_PENDING';
export const MOVIES_FULFILLED = 'MOVIES_FULFILLED';
export const MOVIES_REJECTED = 'MOVIES_REJECTED';

export const MOVIE_DETAIL_PENDING = 'MOVIE_DETAIL_PENDING';
export const MOVIE_DETAIL_FULFILLED = 'MOVIE_DETAIL_FULFILLED';
export const MOVIE_DETAIL_REJECTED = 'MOVIE_DETAIL_REJECTED';
